spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/aiwis_db
    username: aiwis
    password: aiwis
  flyway:
    url: jdbc:postgresql://localhost:5432/aiwis_db
    user: aiwis
    password: aiwis